### ISSUE TITLE
FTPS support is missing in some Java-classes

### ISSUE THREAD

**Issue by BramFC** [Mcpoowl/sFTPs#1]
Hello,

I'm loving the widget so far! Saves me a lot of custom coding. However, it seems you forgot to include the FTPS support in some Java-classes, most notably JA_SendDocument.java.

After including the last line (and an import), we're now also able to upload documents to our FTPS server. This also applies to the rename class (didn't check all of the others).

Ciao!
Bram

`if(SFTPused) {
			SFTPConnection.handleFile(DocumentParameter1, ConfigurationParameter1, ConnectionParameter1, null, context, Action.PUT);
			} else if (type == FTPType.FTP)  {
			reply =	FTPConnection.execute(DocumentParameter1, ConfigurationParameter1, ConnectionParameter1, null, context, Action.PUT);
			} else if (type == FTPType.FTPS)  {
			reply =	FTPSConnection.execute(DocumentParameter1, ConfigurationParameter1, ConnectionParameter1, null, context, Action.PUT);
			}`

**Comment by MichielArts** [comment]
Same issue here, FTPS does not work in JA_SendDocument

**Comment by MichielArts** [comment]
Working FTPS code for some classes


[JA_RenameDocument.java.txt](https://github.com/Mcpoowl/sFTPs/files/3901990/JA_RenameDocument.java.txt)
[JA_SendDocument.java.txt](https://github.com/Mcpoowl/sFTPs/files/3901991/JA_SendDocument.java.txt)
[JA_RemoveDocument.java.txt](https://github.com/Mcpoowl/sFTPs/files/3901992/JA_RemoveDocument.java.txt)

**Comment by ghost** [comment]
The latest version of the module (2.0) in the appstore fixed this issue.

Note that this github repo isn't updated.

@Mcpoowl - Can you close this issue?
